"""Parity checker: replay a TS-generated trace in Python and compare tick-by-tick.

Usage:
    cd training && uv run python parity_check.py

Loads parity_trace.json (generated by parity-trace.ts), replays the same
action sequence through the Python physics, and reports max deltas.

Pass criteria: max position delta < 0.01px, bullet counts match every tick.
"""

from __future__ import annotations

import json
import math
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Load shared constants
# ---------------------------------------------------------------------------
_CONSTANTS_PATH = (
    Path(__file__).resolve().parents[1]
    / "packages"
    / "game-engine"
    / "src"
    / "constants.json"
)
with open(_CONSTANTS_PATH) as _f:
    _C = json.load(_f)

CELL_SIZE: int = _C["CELL_SIZE"]
MAZE_COLS: int = _C["MAZE_COLS"]
MAZE_ROWS: int = _C["MAZE_ROWS"]
ARENA_W: int = MAZE_COLS * CELL_SIZE
ARENA_H: int = MAZE_ROWS * CELL_SIZE
TANK_SPEED: float = _C["TANK_SPEED"]
REVERSE_SPEED_FACTOR: float = _C["REVERSE_SPEED_FACTOR"]
TANK_ROTATION_SPEED: float = _C["TANK_ROTATION_SPEED"]
TANK_WIDTH: int = _C["TANK_WIDTH"]
BARREL_LENGTH: int = _C["BARREL_LENGTH"]
BULLET_SPEED: float = _C["BULLET_SPEED"]
BULLET_LIFETIME: float = _C["BULLET_LIFETIME_SECONDS"]
BULLET_FIRE_COOLDOWN_MS: float = _C["BULLET_FIRE_COOLDOWN_MS"]
MAX_BULLETS: int = _C["MAX_BULLETS_PER_TANK"]
BULLET_RADIUS: int = _C["BULLET_RADIUS"]
CORNER_SHIELD_PADDING: int = _C["CORNER_SHIELD_PADDING"]
WALL_FRICTION: float = _C["WALL_FRICTION"]
SERVER_TICK_HZ: int = _C["SERVER_TICK_HZ"]
DT: float = 1.0 / SERVER_TICK_HZ

# ---------------------------------------------------------------------------
# Action sequence (must match parity-trace.ts)
# ---------------------------------------------------------------------------
ACTION_SEQUENCE = [
    {"up": True, "down": False, "left": False, "right": False, "fire": False},
    {"up": True, "down": False, "left": False, "right": True, "fire": False},
    {"up": False, "down": False, "left": False, "right": False, "fire": True},
]

# ---------------------------------------------------------------------------
# Physics helpers (standalone — not using TankBattleEnv to keep this minimal)
# ---------------------------------------------------------------------------

Seg = tuple[float, float, float, float]
Pt = tuple[float, float]


def compute_obb(angle: float) -> tuple[float, float]:
    rad = math.radians(angle)
    cos_a = abs(math.cos(rad))
    sin_a = abs(math.sin(rad))
    obb = (TANK_WIDTH / 2) * (cos_a + sin_a)
    return rad, obb


def clamp_tank(tank: dict, arena_w: int, arena_h: int) -> None:
    rad, obb = compute_obb(tank["angle"])
    barrel_tip_dist = BARREL_LENGTH + TANK_WIDTH / 2
    bx = barrel_tip_dist * math.cos(rad)
    by = barrel_tip_dist * math.sin(rad)
    right_ext = max(obb, bx if bx > 0 else 0)
    left_ext = max(obb, -bx if bx < 0 else 0)
    bottom_ext = max(obb, by if by > 0 else 0)
    top_ext = max(obb, -by if by < 0 else 0)
    tank["x"] = max(left_ext, min(tank["x"], arena_w - right_ext))
    tank["y"] = max(top_ext, min(tank["y"], arena_h - bottom_ext))


def collide_walls(
    tank: dict, prev: dict, segments: list[Seg]
) -> None:
    """Port of collideTankWithWalls() from physics.ts — OBB + barrel."""
    rad, obb = compute_obb(tank["angle"])
    cos_a = abs(math.cos(rad))
    sin_a = abs(math.sin(rad))
    barrel_dir_x = math.cos(rad)
    barrel_dir_y = math.sin(rad)
    barrel_tip_dist = BARREL_LENGTH + TANK_WIDTH / 2
    barrel_ext_x = max(obb, barrel_tip_dist * cos_a)
    barrel_ext_y = max(obb, barrel_tip_dist * sin_a)

    x = tank["x"]
    y = tank["y"]

    for seg in segments:
        x1, y1, x2, y2 = seg
        if x1 == x2:  # vertical wall
            wx = x1
            mn_y = min(y1, y2)
            mx_y = max(y1, y2)
            from_left = prev["x"] <= wx
            barrel_faces = barrel_dir_x > 0 if from_left else barrel_dir_x < 0
            rx = barrel_ext_x if barrel_faces else obb
            if y + barrel_ext_y >= mn_y and y - barrel_ext_y <= mx_y and abs(x - wx) <= rx:
                x = wx - rx if from_left else wx + rx
                slide_y = y - prev["y"]
                y = prev["y"] + slide_y * (1 - WALL_FRICTION)
        elif y1 == y2:  # horizontal wall
            wy = y1
            mn_x = min(x1, x2)
            mx_x = max(x1, x2)
            from_top = prev["y"] <= wy
            barrel_faces = barrel_dir_y > 0 if from_top else barrel_dir_y < 0
            ry = barrel_ext_y if barrel_faces else obb
            if x + barrel_ext_x >= mn_x and x - barrel_ext_x <= mx_x and abs(y - wy) <= ry:
                y = wy - ry if from_top else wy + ry
                slide_x = x - prev["x"]
                x = prev["x"] + slide_x * (1 - WALL_FRICTION)

    tank["x"] = x
    tank["y"] = y


def collide_endpoints(tank: dict, endpoints: list[Pt]) -> None:
    _, obb = compute_obb(tank["angle"])
    sr = obb + CORNER_SHIELD_PADDING
    for pt in endpoints:
        dx = tank["x"] - pt[0]
        dy = tank["y"] - pt[1]
        dsq = dx * dx + dy * dy
        if dsq < sr * sr and dsq > 0:
            d = math.sqrt(dsq)
            tank["x"] = pt[0] + (dx / d) * sr
            tank["y"] = pt[1] + (dy / d) * sr


def bullet_crosses_wall(
    px: float, py: float, nx: float, ny: float, seg: Seg
) -> tuple[bool, float, float]:
    sx1, sy1, sx2, sy2 = seg
    if sx1 == sx2:
        wx = sx1
        mn_y, mx_y = min(sy1, sy2), max(sy1, sy2)
        if min(px, nx) <= wx <= max(px, nx):
            dx = nx - px
            if abs(dx) < 0.001:
                return False, 0.0, 0.0
            t = (wx - px) / dx
            hy = py + t * (ny - py)
            if mn_y <= hy <= mx_y:
                return True, wx, hy
    elif sy1 == sy2:
        wy = sy1
        mn_x, mx_x = min(sx1, sx2), max(sx1, sx2)
        if min(py, ny) <= wy <= max(py, ny):
            dy = ny - py
            if abs(dy) < 0.001:
                return False, 0.0, 0.0
            t = (wy - py) / dy
            hx = px + t * (nx - px)
            if mn_x <= hx <= mx_x:
                return True, hx, wy
    return False, 0.0, 0.0


def reflect_at_wall(
    bullet: dict, seg: Seg, hx: float, hy: float
) -> None:
    sx1, sy1, sx2, sy2 = seg
    eps = BULLET_RADIUS + 1
    if sx1 == sx2:
        bullet["vx"] = -bullet["vx"]
        bullet["x"] = hx + eps if bullet["vx"] > 0 else hx - eps
        bullet["y"] = hy
    elif sy1 == sy2:
        bullet["vy"] = -bullet["vy"]
        bullet["x"] = hx
        bullet["y"] = hy + eps if bullet["vy"] > 0 else hy - eps


def create_bullet(
    bid: int, tank: dict, segments: list[Seg]
) -> dict:
    rad = math.radians(tank["angle"])
    sd = BARREL_LENGTH + TANK_WIDTH / 2
    tx = tank["x"] + math.cos(rad) * sd
    ty = tank["y"] + math.sin(rad) * sd
    vx = math.cos(rad) * BULLET_SPEED
    vy = math.sin(rad) * BULLET_SPEED
    b = {"id": bid, "x": tx, "y": ty, "vx": vx, "vy": vy, "age": 0.0}
    for seg in segments:
        crossed, hx, hy = bullet_crosses_wall(tank["x"], tank["y"], tx, ty, seg)
        if crossed:
            reflect_at_wall(b, seg, hx, hy)
            return b
    return b


def advance_bullet(bullet: dict, segments: list[Seg]) -> bool:
    """Advance bullet one tick. Returns False if expired."""
    prev_x, prev_y = bullet["x"], bullet["y"]
    bullet["x"] += bullet["vx"] * DT
    bullet["y"] += bullet["vy"] * DT
    bullet["age"] += DT
    if bullet["age"] >= BULLET_LIFETIME:
        return False
    # Wall reflection
    for seg in segments:
        crossed, hx, hy = bullet_crosses_wall(prev_x, prev_y, bullet["x"], bullet["y"], seg)
        if crossed:
            dx_t = bullet["x"] - prev_x
            dy_t = bullet["y"] - prev_y
            total = math.sqrt(dx_t * dx_t + dy_t * dy_t)
            reflect_at_wall(bullet, seg, hx, hy)
            if total > 0.001:
                hdx = hx - prev_x
                hdy = hy - prev_y
                hit_d = math.sqrt(hdx * hdx + hdy * hdy)
                remain = total - hit_d
                spd = math.sqrt(bullet["vx"] ** 2 + bullet["vy"] ** 2)
                if spd > 0:
                    bullet["x"] += (bullet["vx"] / spd) * remain
                    bullet["y"] += (bullet["vy"] / spd) * remain
            break
    return True


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    trace_path = Path(__file__).parent.parent / "parity_trace.json"
    if not trace_path.exists():
        print(f"ERROR: {trace_path} not found. Run:")
        print("  pnpm exec tsx packages/game-engine/scripts/parity-trace.ts")
        sys.exit(1)

    with open(trace_path) as f:
        data = json.load(f)

    segments: list[Seg] = [
        (s["x1"], s["y1"], s["x2"], s["y2"]) for s in data["wallSegments"]
    ]
    endpoints: list[Pt] = [(e["x"], e["y"]) for e in data["endpoints"]]
    spawn = data["spawns"][0]
    ts_trace = data["trace"]

    tank = {"x": float(spawn["x"]), "y": float(spawn["y"]), "angle": 0.0, "speed": 0.0}
    bullets: list[dict] = []
    last_fired_at = -999999.0
    bullet_id = 0

    max_dx = 0.0
    max_dy = 0.0
    max_da = 0.0
    bullet_mismatches = 0
    first_mismatch_tick: int | None = None

    for tick in range(len(ts_trace)):
        action = ACTION_SEQUENCE[tick % len(ACTION_SEQUENCE)]
        prev = dict(tank)

        # Rotation
        if action["left"]:
            tank["angle"] -= TANK_ROTATION_SPEED * DT
        if action["right"]:
            tank["angle"] += TANK_ROTATION_SPEED * DT
        tank["angle"] = tank["angle"] % 360.0

        # Movement
        speed = 0.0
        if action["up"]:
            speed = TANK_SPEED
        elif action["down"]:
            speed = -TANK_SPEED * REVERSE_SPEED_FACTOR
        tank["speed"] = speed
        rad = math.radians(tank["angle"])
        tank["x"] += math.cos(rad) * speed * DT
        tank["y"] += math.sin(rad) * speed * DT

        # Clamp -> wall collision -> endpoint collision
        clamp_tank(tank, ARENA_W, ARENA_H)
        collide_walls(tank, prev, segments)
        collide_endpoints(tank, endpoints)

        # Fire
        now = tick * (1000.0 / SERVER_TICK_HZ)
        if action["fire"] and (now - last_fired_at) >= BULLET_FIRE_COOLDOWN_MS and len(bullets) < MAX_BULLETS:
            bullets.append(create_bullet(bullet_id, tank, segments))
            bullet_id += 1
            last_fired_at = now

        # Advance bullets
        bullets = [b for b in bullets if advance_bullet(b, segments)]

        # Compare with TS trace
        ts = ts_trace[tick]
        py_x = round(tank["x"], 4)
        py_y = round(tank["y"], 4)
        py_a = round(tank["angle"], 4)

        dx = abs(py_x - ts["x"])
        dy = abs(py_y - ts["y"])
        da = abs(py_a - ts["angle"])
        max_dx = max(max_dx, dx)
        max_dy = max(max_dy, dy)
        max_da = max(max_da, da)

        if len(bullets) != ts["bulletCount"]:
            bullet_mismatches += 1
            if first_mismatch_tick is None:
                first_mismatch_tick = tick
                print(f"  FIRST bullet count mismatch at tick {tick}: "
                      f"py={len(bullets)} ts={ts['bulletCount']}")

        if dx > 0.01 or dy > 0.01:
            if tick < 20 or (tick % 100 == 0):
                print(f"  tick {tick}: pos delta ({dx:.6f}, {dy:.6f}) "
                      f"py=({py_x}, {py_y}) ts=({ts['x']}, {ts['y']})")

    print(f"\n=== Parity Check Results ({len(ts_trace)} ticks) ===")
    print(f"Max position delta X: {max_dx:.6f} px")
    print(f"Max position delta Y: {max_dy:.6f} px")
    print(f"Max angle delta:      {max_da:.6f} deg")
    print(f"Bullet count mismatches: {bullet_mismatches}")

    pos_ok = max(max_dx, max_dy) < 0.01
    bullet_ok = bullet_mismatches == 0
    if pos_ok and bullet_ok:
        print("\nPASS: Python physics matches TS reference within tolerance.")
    else:
        if not pos_ok:
            print(f"\nFAIL: Position delta {max(max_dx, max_dy):.6f} >= 0.01 px")
        if not bullet_ok:
            print(f"FAIL: {bullet_mismatches} bullet count mismatches")
        sys.exit(1)


if __name__ == "__main__":
    main()
